### ISSUE TITLE
Merge arcfn.com into righto.com

### ISSUE THREAD

**Issue by shirriff** [mtlynch/hn-popularity-contest-data#42]
The methodology page says that you aggregate domains where the author moved domains. My domain arcfn.com is now merged into righto.com; righto.com is the canonical domain. If you can merge the domains without too much effort, I'd appreciate it.

**Comment by mtlynch** [comment]
Sure thing!

The merging logic isn't in the repo yet, but I've just fixed it. You're now at \#9, unseating Troy Hunt.

**Comment by shirriff** [comment]
I don't see any change. righto.com was at #8 with 41,876 before and it is still the same. Not that it matters, just letting you know in case the merge logic has a problem.

**Comment by mtlynch** [comment]
Oh, sorry. I remembered you being at 9, but you're right that you were 8 before the merge.

With the merge, you have a total of 43,459. I'm not sure if the CDN was just caching the old one or if I somehow forgot to push after merging, but it's fixed now:

![Image](https://github.com/user-attachments/assets/be9abca3-3976-4b54-92b4-0d95977455d6)

Thanks for letting me know!

**Comment by shirriff** [comment]
Thanks! I'm seeing the update now.
